const ORIGINAL_DATA = [
  { word: "hello", fa: "", ch: "你好", de: "hallo" },
  { word: "goodbye", fa: "خداحافظ", ch: "再见", de: "auf Wiedersehen" },
  { word: "please", fa: "لطفا", ch: "请", de: "bitte" },
  { word: "thank you", fa: "متشکرم", ch: "谢谢", de: "danke" },
  { word: "yes", fa: "بله", ch: "是", de: "ja" },
  { word: "no", fa: "نه", ch: "不", de: "nein" },
  { word: "friend", fa: "دوست", ch: "朋友", de: "freund" },
  { word: "family", fa: "خانواده", ch: "家庭", de: "familie" },
  { word: "love", fa: "عشق", ch: "爱", de: "liebe" },
  { word: "water", fa: "آب", ch: "水", de: "wasser" },
  { word: "food", fa: "غذا", ch: "食物", de: "essen" },
  { word: "house", fa: "خانه", ch: "房子", de: "haus" },
  { word: "school", fa: "مدرسه", ch: "学校", de: "schule" },
  { word: "book", fa: "کتاب", ch: "书", de: "buch" },
  { word: "car", fa: "ماشین", ch: "汽车", de: "auto" },
  { word: "city", fa: "شهر", ch: "城市", de: "stadt" },
  { word: "country", fa: "کشور", ch: "国家", de: "land" },
  { word: "work", fa: "کار", ch: "工作", de: "arbeit" },
  { word: "day", fa: "روز", ch: "天", de: "tag" },
  { word: "night", fa: "شب", ch: "夜晚", de: "nacht" },
  { word: "sun", fa: "خورشید", ch: "太阳", de: "sonne" },
  { word: "moon", fa: "ماه", ch: "月亮", de: "mond" },
  { word: "star", fa: "ستاره", ch: "星星", de: "stern" },
  { word: "tree", fa: "درخت", ch: "树", de: "baum" },
  { word: "flower", fa: "گل", ch: "花", de: "blume" },
  { word: "river", fa: "رودخانه", ch: "河流", de: "fluss" },
  { word: "mountain", fa: "کوه", ch: "山", de: "berg" },
  { word: "rain", fa: "باران", ch: "雨", de: "regen" },
  { word: "snow", fa: "برف", ch: "雪", de: "schnee" },
  { word: "wind", fa: "باد", ch: "风", de: "wind" },
  { word: "fire", fa: "آتش", ch: "火", de: "feuer" },
  { word: "earth", fa: "زمین", ch: "地球", de: "erde" },
  { word: "air", fa: "هوا", ch: "空气", de: "luft" },
  { word: "phone", fa: "تلفن", ch: "电话", de: "telefon" },
  { word: "computer", fa: "رایانه", ch: "电脑", de: "computer" },
  { word: "music", fa: "موسیقی", ch: "音乐", de: "musik" },
  { word: "movie", fa: "فیلم", ch: "电影", de: "film" },
  { word: "game", fa: "بازی", ch: "游戏", de: "spiel" },
  { word: "sport", fa: "ورزش", ch: "运动", de: "sport" },
  { word: "happy", fa: "خوشحال", ch: "高兴", de: "glücklich" },
  { word: "sad", fa: "ناراحت", ch: "难过", de: "traurig" },
  { word: "fast", fa: "سریع", ch: "快", de: "schnell" },
  { word: "slow", fa: "آهسته", ch: "慢", de: "langsam" },
  { word: "big", fa: "بزرگ", ch: "大", de: "groß" },
  { word: "small", fa: "کوچک", ch: "小", de: "klein" },
  { word: "hot", fa: "گرم", ch: "热", de: "heiß" },
  { word: "cold", fa: "سرد", ch: "冷", de: "kalt" },
  { word: "new", fa: "جدید", ch: "新", de: "neu" },
  { word: "old", fa: "قدیمی", ch: "旧", de: "alt" },
  { word: "young", fa: "جوان", ch: "年轻", de: "jung" },
  { word: "beautiful", fa: "زیبا", ch: "漂亮", de: "schön" },
  { word: "ugly", fa: "زشت", ch: "丑", de: "hässlich" },
  { word: "strong", fa: "قوی", ch: "强壮", de: "stark" },
  { word: "weak", fa: "ضعیف", ch: "弱", de: "schwach" },
  { word: "easy", fa: "آسان", ch: "容易", de: "einfach" },
  { word: "hard", fa: "سخت", ch: "难", de: "schwierig" },
  { word: "clean", fa: "تمیز", ch: "干净", de: "sauber" },
  { word: "dirty", fa: "کثیف", ch: "脏", de: "schmutzig" },
  { word: "rich", fa: "ثروتمند", ch: "富有", de: "reich" },
  { word: "poor", fa: "فقیر", ch: "贫穷", de: "arm" },
  { word: "light", fa: "روشن", ch: "亮", de: "hell" },
  { word: "dark", fa: "تاریک", ch: "暗", de: "dunkel" },
  { word: "early", fa: "زود", ch: "早", de: "früh" },
  { word: "late", fa: "دیر", ch: "晚", de: "spät" },
  { word: "friendship", fa: "دوستی", ch: "友谊", de: "freundschaft" },
  { word: "peace", fa: "صلح", ch: "和平", de: "friend" },
  { word: "war", fa: "جنگ", ch: "战争", de: "krieg" },
  { word: "freedom", fa: "آزادی", ch: "自由", de: "freiheit" },
  { word: "power", fa: "قدرت", ch: "力量", de: "macht" },
  { word: "hope", fa: "امید", ch: "希望", de: "hoffnung" },
  { word: "dream", fa: "رویا", ch: "梦想", de: "traum" },
  { word: "fear", fa: "ترس", ch: "恐惧", de: "angst" },
  { word: "joy", fa: "شادی", ch: "快乐", de: "freude" },
  { word: "anger", fa: "خشم", ch: "愤怒", de: "wut" },
  { word: "health", fa: "سلامتی", ch: "健康", de: "gesundheit" },
  { word: "sickness", fa: "بیماری", ch: "疾病", de: "krankheit" },
  { word: "money", fa: "پول", ch: "钱", de: "geld" },
  { word: "time", fa: "زمان", ch: "时间", de: "zeit" },
  { word: "teacher", fa: "معلم", ch: "老师", de: "lehrer" },
  { word: "student", fa: "دانش‌آموز", ch: "学生", de: "schüler" },
  { word: "bus", fa: "اتوبوس", ch: "公交车", de: "bus" },
  { word: "train", fa: "قطار", ch: "火车", de: "zug" },
  { word: "plane", fa: "هواپیما", ch: "飞机", de: "flugzeug" },
  { word: "ship", fa: "کشتی", ch: "船", de: "schiff" },
  { word: "boat", fa: "قایق", ch: "小船", de: "boot" },
  { word: "road", fa: "جاده", ch: "道路", de: "straße" },
  { word: "street", fa: "خیابان", ch: "街道", de: "gasse" },
  { word: "park", fa: "پارک", ch: "公园", de: "park" },
  { word: "market", fa: "بازار", ch: "市场", de: "markt" },
  { word: "store", fa: "فروشگاه", ch: "商店", de: "geschäft" },
  { word: "shop", fa: "فروشگاه", ch: "店铺", de: "laden" },
  { word: "restaurant", fa: "رستوران", ch: "餐厅", de: "restaurant" },
  { word: "hotel", fa: "هتل", ch: "酒店", de: "hotel" },
  { word: "hospital", fa: "بیمارستان", ch: "医院", de: "krankenhaus" },
  { word: "police", fa: "پلیس", ch: "警察", de: "polizei" },
  { word: "firefighter", fa: "آتش‌نشان", ch: "消防员", de: "feuerwehrmann" },
];

export const INITIAL_DATA = ORIGINAL_DATA.map((item) => ({
  ...item,
  word: item.word.charAt(0).toUpperCase() + item.word.slice(1),
  de: item.de.charAt(0).toUpperCase() + item.de.slice(1),
}));

export function sortByWord(data, order = "asc") {
  return [...data].sort((a, b) => {
    const wordA = a.word.toLowerCase();
    const wordB = b.word.toLowerCase();

    if (order === "asc") {
      return wordA.localeCompare(wordB);
    } else {
      return wordB.localeCompare(wordA);
    }
  });
}
